# Chapter 13 - Dictionaries

---

Strings and lists are ordered data structures, which entails that they can be indexed. Not all data is naturally ordered, which is why Python offers dictionaries as a way to structure unordered data.

---

## Basics of dictionaries

Dictionaries are *unordered* collections of elements. To identify an element, you have to know the element's "key".

Basically, dictionaries store "key-value pairs". Any immutable data type can function as a key. A very common type to use as key is the string.

You create dictionaries using curly brackets (`{}`), similar to how you create lists using square brackets. An empty dictionary you create by assigning `{}` to a variable. You can create a dictionary with contents by describing every element of the dictionary between the curly brackets using the syntax `<key>:<value>`, and commas between the elements.

Here a dictionary `fruitbasket` is created, that contains three key-value pairs, namely the key "apple" with value 3, the key "banana" with value 5, and the key "cherry" with value 50.

In [1]:
fruitbasket = { "apple":3, "banana":5, "cherry":50 }
print(fruitbasket)

{'apple': 3, 'banana': 5, 'cherry': 50}

To access the value belonging to a specific key, you use the same syntax as you would use for a list, except that you write the key in the place where you would write the index for a list.

In [2]:
fruitbasket = { "apple":3, "banana":5, "cherry":50 }
print(fruitbasket)
print( fruitbasket["apple"] )

{'apple': 3, 'banana': 5, 'cherry': 50}
3

You can use a `for` loop to traverse a dictionary. The variable in the `for` loop gets access to all the keys.

In [3]:
fruitbasket = { "apple":3, "banana":5, "cherry":50 }

def traverse_dictionary(dictionary):
    content = ""
    for key in dictionary:
        #content += ( "{}:{}\n".format( key, dictionary[key] ))       #?¿?¿?¿?¿?¿?¿
        content += key + ":" + str(dictionary[key])+ "\n"
    return content

print(traverse_dictionary(fruitbasket))

apple:3
banana:5
cherry:50

Trying to access a dictionary element using a key that is not available in the dictionary will lead to a runtime error. However, adding a new element to a dictionary you can do by simply assigning a value to the dictionary item identified by the new key. For instance, adding a "mango" to the fruitbasket you can do as follows:

In [4]:
fruitbasket = { "apple":3, "banana":5, "cherry":50 }
print( fruitbasket )
fruitbasket["mango"]  =3
print(fruitbasket)

{'apple': 3, 'banana': 5, 'cherry': 50}
{'apple': 3, 'banana': 5, 'cherry': 50, 'mango': 3}

In [5]:
fruitbasket["mango"] +=3
print( fruitbasket )

{'apple': 3, 'banana': 5, 'cherry': 50, 'mango': 6}

Overwriting a dictionary item works in exactly the same way as creating a new dictionary item: you just assign a value to it.

Deleting an item from a dictionary you do using the `del` keyword, just as you can use with lists.

In [6]:
fruitbasket = { "apple":3, "banana":5, "cherry":50 }
print( fruitbasket )
del fruitbasket["banana"]
print( fruitbasket )
del fruitbasket["cherry"]
print(fruitbasket)

{'apple': 3, 'banana': 5, 'cherry': 50}
{'apple': 3, 'cherry': 50}
{'apple': 3}

In [7]:
print(len(fruitbasket))

1

In [8]:
print(type(fruitbasket))

<class 'dict'>

You can determine the number of key-value pairs in a dictionary by using the `len()` function.

By the way, do you understand how the ordering of a dictionary works when looking at the display of a dictionary? Think about it.

The answer is: there is no ordering. That was what I said at the start: dictionaries are unordered. In principle I cannot even tell you what ordering you see on your screen when you run the code above, because it might differ between computers, operating systems, and versions of Python. There is a certain structure to the ordering of the items, but nothing that you can (or should desire to) predict. By adding enough items, the ordering might even suddenly change completely.

Since dictionaries are unordered, many of the concepts that are applicable to lists, do not work on dictionaries. For instance, you cannot refer to "slices" of a dictionary, and neither can you "sort" or "reverse" a dictionary. So dictionaries are quite limited, but they do have their uses.

---

## Dictionary methods

This section describes the dictionary methods that are most often used.

### `copy()`

Just like lists, if you assign a variable that contains a dictionary to another variable, you are not creating a copy of the dictionary; you are actually creating an alias (if you do not remember what an alias is, see the previous chapter). You cannot use the trick which is used for lists to create a copy, as it uses a slice-syntax, and dictionaries do not support slices. Therefore, there is a method `copy()` that returns a copy of a dictionary.

In [9]:
fruitbasket = { "apple":3, "banana":5, "cherry":50 }
fruitbasketalias = fruitbasket
fruitbasketcopy = fruitbasket.copy()

print( id( fruitbasket ) )
print( id( fruitbasketalias ) )
print( id( fruitbasketcopy ) )

2615138761032
2615138761032
2615138760888

Note that this method makes a shallow copy of the dictionary (see the previous chapter if you do not remember the difference between shallow and deep copies). If you want to make a deep copy, use the `deepcopy()` function from the `copy` module.

### `keys()`, `values()`, and `items()`

The method `keys()` provides an iterator that lists all the keys of a dictionary. The method `values()` provides an iterator that lists all the values of a dictionary. The method `items()` provides an iterator that lists all the key-value pairs of a dictionary as tuples.

I specifically say that these methods returns an iterator and not a list. If you want to turn them into lists, you have to use list casting (see the previous chapter).

In [10]:
fruitbasket = { "apple":3, "banana":5, "cherry":50 }
print( list(fruitbasket.keys() ) )
print( list( fruitbasket.values() ) )
print( list( fruitbasket.items() ) )

['apple', 'banana', 'cherry']
[3, 5, 50]
[('apple', 3), ('banana', 5), ('cherry', 50)]

At this point you might be wondering when you can use an iterator. You mainly use iterators for `for` loops (though you can also use them as arguments for the functions `max()`, `min()` and `sum()`).

In [11]:
fruitbasket = { "apple":3, "banana":5, "cherry":50, "durian":0, "mango":2 }
for key in fruitbasket.keys():
    print( "{}:{}".format( key, fruitbasket[key] ) )
    
print( sum( fruitbasket.values() ) )

apple:3
banana:5
cherry:50
durian:0
mango:2
60

Since this code provides an unpredictable order for the keys, you might want to sort them before looping over them. Since `keys()` does not provide a list, it cannot be sorted directly, but you can turn the result into a list using list casting. After doing that, you can sort.

In [12]:
fruitbasket = { "apple":3, "banana":5, "cherry":50, "durian":0, "mango":2 }
keylist = list( fruitbasket.keys() )
keylist.sort()
print(keylist)
for key in keylist:
    print( "{}:{}".format( key, fruitbasket[key] ) )

['apple', 'banana', 'cherry', 'durian', 'mango']
apple:3
banana:5
cherry:50
durian:0
mango:2

You cannot apply the `sort()` method to the list casting, i.e., `keylist = list( fruitbasket.key() ).sort()` does not work. You must first create the list, then sort it. Neither can you write `for key in keylist.sort()`, as the `sort()` method has no return value.

If you wonder why Python seems to prefer iterators instead of lists: the answer is that iterators are more general and use much less memory. They are "lazy" methods, as they only provide an item when it is requested.

### `get()`

The `get()` method can be used to get a value from a dictionary even when you do not know if the key for which you seek the value exists. You call the `get()` method with the key you are looking for, and it will return the corresponding value when the key exists in the dictionary, or the special value `None` when the key does not exist in the dictionary. If you want to return a specific value instead of `None` if the key does not exist, you can add that value as a second argument to the method.

In [13]:
fruitbasket = { "apple":3, "banana":5, "cherry":50, "durian":0, "mango":2 }
print(fruitbasket.get("love",5))
print(fruitbasket["apple"])
print(fruitbasket)

5
3
{'apple': 3, 'banana': 5, 'cherry': 50, 'durian': 0, 'mango': 2}

In [14]:
fruitbasket = { "apple":3, "banana":5, "cherry":50, "durian":0, "mango":2 }


def keyvalue_exists(fruitbasket, item): 
    apple = fruitbasket.get( item )
    output = ""
    if apple:
        return (item + " is in the basket" )
    else:
        return( "no "+ item + " in the basket")
        
print(keyvalue_exists(fruitbasket, "apple"))
print(keyvalue_exists(fruitbasket, "orange"))

banana = fruitbasket.get( "banana", 0 )
print( "number of bananas in the basket:", banana )

strawberry = fruitbasket.get( "strawberry", 0 )
print( "number of strawberries in the basket:", strawberry )

apple is in the basket
no orange in the basket
number of bananas in the basket: 5
number of strawberries in the basket: 0

Study the example above closely, as what it demonstrates about the `get()` method is very useful. Suppose that you store a collection of items with corresponding quantities, for instance, the contents of a fruit basket with the keys being the names of the fruits and the values being the quantities. When you query the fruitbasket dictionary using the `get()` method with a second parameter zero, you can look for any fruit in the basket without the need to check first if the fruit exists in the basket, because if you ask for a fruit that is not there, the `get()` method returns zero, which is exactly what you want to hear.

### Practice

**Exercise**: The code block below contains a list of words. Build a dictionary that contains all these words as keys, and how often they occur as values. Then print the words with their quantities.

In [15]:
# Word counts.
wordlist = ["apple","durian","banana","durian","apple","cherry","cherry","mango","apple",
            "apple","cherry","durian","banana","apple","apple","apple","apple","banana","apple"]

dic = {}

for i in wordlist:
    if i not in dic:
        dic[i] = 0
    if i in dic:
        dic[i] += 1
    
print(dic)

{'apple': 9, 'durian': 3, 'banana': 3, 'cherry': 3, 'mango': 1}

**Exercise**: The code block below contains a string that is a list of words, separated by commas. Build a dictionary that contains all these words as keys, and how often they occur as values. Then print the words with their quantities.

In [16]:
# More word counts.
csv = "apple,durian,banana,durian,apple,cherry,cherry,mango,apple," + \
      "apple,cherry,durian,banana,apple,apple,apple,apple,banana,apple"
    
listword = csv.split(",")
print(listword)
dic2 = {}
for i in listword:
    if i not in dic2:
        dic2[i] = 0
    if i in dic2:
        dic2[i] += 1
print(dic2)

['apple', 'durian', 'banana', 'durian', 'apple', 'cherry', 'cherry', 'mango', 'apple', 'apple', 'cherry', 'durian', 'banana', 'apple', 'apple', 'apple', 'apple', 'banana', 'apple']
{'apple': 9, 'durian': 3, 'banana': 3, 'cherry': 3, 'mango': 1}

**Exercise**: The code block below contains a very small dictionary that contains the translations of English words to Dutch. Write a program that uses this dictionary to create a word-for-word translation of the given sentence. A word for which you cannot find a translation, you can leave "as is". The dictionary is supposed to be used case-insensitively, but your translation may consist of all lower case words. It is nice if you leave punctuation in the translation, but if you take it out, that is acceptable (as leaving punctuation in is quite a bit of work, and does not really have anything to do with dictionaries -- besides, leaving punctuation in is much easier to do once you have learned about regular expressions).

In [17]:
# Translation
english_spanish = { "last":"ultima", "week":"semana", "the":"el",
    "royal":"real", "festival":"festival", "hall":"hall",
    "saw":"vió", "first":"primero", "performance":"función",
    "of":"de", "a":"un", "new":"nuevo", "symphony":"sinfonia",
    "by":"por", "one":"uno", "world":"mundo", "leading":"liderando",
    "modern":"moderno", "composer":"compositor", "composers":"compositores",
    "two":"dos", "shed":"xx", "sheds":"yy" }

sentence = "Last week The Royal Festival Hall saw the first performance of \
a new symphony by one of the world's leading modern composers, Arthur \"Two-Sheds\" Jackson."

listsentence = sentence.split()
print(listsentence)
print("")

stripedlist = []
for i in listsentence:
    clean_words = i.strip(".,!?\n""\ ").lower()
    stripedlist.append(clean_words)
print(stripedlist)
print("")

translist = []

for i in stripedlist:
    if i in english_dutch:
        translist.append(english_spanish[i])
    if i not in english_spanish:
        translist.append("-")
    
print(translist)
print("")

traduction = ""
for i in translist:
    traduction += (i + " ")
print(traduction)

['Last', 'week', 'The', 'Royal', 'Festival', 'Hall', 'saw', 'the', 'first', 'performance', 'of', 'a', 'new', 'symphony', 'by', 'one', 'of', 'the', "world's", 'leading', 'modern', 'composers,', 'Arthur', '"Two-Sheds"', 'Jackson.']

['last', 'week', 'the', 'royal', 'festival', 'hall', 'saw', 'the', 'first', 'performance', 'of', 'a', 'new', 'symphony', 'by', 'one', 'of', 'the', "world's", 'leading', 'modern', 'composers', 'arthur', '"two-sheds"', 'jackson']

NameError: name 'english_dutch' is not defined

---

## Keys

As I said, any immutable data type can be a dictionary key. This means that strings, integers, and floats can all be used as keys. This can occasionally be useful. 

A very straightforward example of tuples being useful as keys is a dictionary in which you want to store information associated with points in two-dimensional space (a discussion of which was given in the chapter on tuples). There is no good way in which you can store the identification of a point in a single number or string. It is not impossible (for instance, you could store the number-pair as their string-representations, concatenated with a comma in between) but it becomes ambiguous and convoluted (for instance, the string-keys "`2,3`", "`2, 3`", "`+2,+3`", and "`02,03`" would all be representing the same tuple).

---

## Storing complicated values

Until now I only considered the case in which a dictionary stores a single value of a simple data type. However, it is possible to store much more complex values in dictionaries. Values can be arbitrary Python objects. For example, you can store a list with each key. Below a dictionary is used to store the students who are following a course. The course is identified by its course number, while the students are identified by their student numbers.

In [ ]:
courses = {
    '880254':['u123456', 'u383213', 'u234178'], 
    '822177':['u123456', 'u223416', 'u234178'], 
    '822164':['u123456', 'u223416', 'u383213', 'u234178']}

for c in courses:
    print( c )
    
    for s in courses[c]:
        print( s, end=" " )
        
    print()
    print(" ")

Suppose that we do not only want to store the student numbers for a course number, but also the name of the course, the ECTS value of the course, and for each student number also the grade. You can do that (for example) by storing the value for a course number as a dictionary, with three keys, namely "name", "ects", and "students". The value for "name" is the course name as a string, the value for "ects" is the ECTS as an integer, and the value for "students" is another dictionary, which contains student numbers as keys and grades as values.

In [ ]:
courses = {
    '880254': 
    { "name":"Research Skills Data Processing", "ects":3, 
      "students":{'u123456':8, 'u383213':7.5, 'u234178':6} }, 
    '822177': 
    { "name":"Understanding Intelligence", "ects":6,
     "students":{'u123456':5, 'u223416':7, 'u234178':9} }, 
    '822164': 
    { "name":"Computer Games", "ects":6,
     "students":{'u123456':7.5, 'u223416':9, 'u383213':6, 'u234178':4} } }

for c in courses:
    print( "{}: {} ({})".format( c, courses[c]["name"], courses[c]["ects"] ) )
    for s in courses[c]["students"]:
        print( "{}: {}".format( s, courses[c]["students"][s] ) )
    print()

Data structures can become a lot more complex than this if you want. However, if you are really considering designing Python programs for data structures like this, you should at least investigate object orientation first and probably do a separate course on databases.

---

## Lookup speed

Lists and dictionaries are the two most-used data structures in Python. While often it is clear when you should use which data structure, it is helpful if you know a little bit about how Python processes these data structures in case you have a choice.

Suppose that we read a large bunch of numbers from a file. The numbers are all different and can be anything. We later need to compare the numbers on another list to the numbers that we read from the file.

Should we use a list or a dictionary to store the numbers that we read from the file? Since they are just numbers, without extra data, a list seems to be the best option. There is, however, a problem if you use a list here. Check out the following code, in which a list of 10000 numbers is created, and after that some code checks for 10000 different numbers whether they are on the list (which none of them are).

In [ ]:
from datetime import datetime


def duration_check_numbers_in_list():
    numlist = []

    for i in range( 10000 ):
        numlist.append( i )

    start = datetime.now()

    count = 0
    for i in range( 10000, 20000 ):
        if i in numlist:
            count += 1

    end = datetime.now()
    return( "{}.{} seconds needed to find {} numbers".format( 
            (end - start).seconds, (end - start).microseconds,count ) )
print(duration_check_numbers_in_list())

Here is the code for doing the same thing with a dictionary, where we simply store the value 1 with each number.

In [ ]:
from datetime import datetime

def duration_check_numbers_in_dictionary():
    numdict = {}

    for i in range( 10000 ):
        numdict[i] = 1

    start = datetime.now()

    count = 0
    for i in range( 10000, 20000 ):
        if i in numdict:
            count += 1

    end = datetime.now()

    return( "{}.{} seconds needed to find {} numbers".format( 
            (end - start).seconds, (end - start).microseconds,count ) )
print(duration_check_numbers_in_dictionary())

You will notice that for a dictionary, the code gives an answer almost immediately, while for a list it takes quite some time for the code to provide an answer. 

The reason is that I use the `in` operator to check whether a number is in the list, or in the dictionary. For a list this means that Python searches through the list, sequentially, until it reaches the number or reaches the end of the list. In this case, it means that Python checks 10000 times 10000 numbers (as it cannot find any of them), which is 100 million numbers.

For a dictionary, the process of finding a key is much faster. Python can quickly decide whether or not a key is in a dictionary. Usually, the checking of just a handful of numbers suffices. Therefore, the code is much, much faster for a dictionary.

You might think that a couple of seconds for the list search is still negligible, but the search time increases quadratically with the size of the data. Depending on the problem, using a dictionary might be highly preferable over using a list.

On the other hand, lists take less memory than dictionaries, and if you can directly access a list item via its index, lists are faster than dictionaries. For instance, in the problem above, if the list is sorted you can find numbers on it in a smarter way than using the `in` operator (checking about 14 indices would suffice) -- in that case, a list may be faster again.

From this, you should remember that a list is fast if you can access its elements directly via their index, while a dictionary is a much better choice if the main way to find something is by scanning items. The `in` operator seems easy and reads well, but if you use it to seek something in a long list, you better think again.

---

## What you learned

In this chapter, you learned about:

- Dictionaries
- Dictionary keys and values
- Dictionary methods `copy()`, `keys()`, `values()`, `items()`, and `get()`
- Complicated dictionaries
- Speed differences between lists and dictionaries

---

## Excercises

### Exercise 13.1

Write a program that takes the text in the code block, splits it into words (where everything that is not a letter is considered a word boundary), and case-insensitively builds a dictionary that stores for every word how often it occurs in the text. Then print all the words with their quantities in alphabetical order.

In [ ]:
# Word counting.
text = """How much wood would a woodchuck chuck
If a woodchuck could chuck wood?
He would chuck, he would, as much as he could,
And chuck as much as a woodchuck would
If a woodchuck could chuck wood."""

words = text.split()
print(words)
print()

clean_words = []

for i in words:
    clean_word = i.strip(".,!?").lower()
    clean_words.append(clean_word)
    
print(clean_words)
print()

dic = {}
for i in clean_words:
    if i not in dic:
        dic[i] = 0
    if i in dic:
        dic[i] += 1
print(dic)

### Exercise 13.2

The code block below shows a list of movies. For each movie it also shows a list of ratings. Convert this code in such a way that it stores all this data in one dictionary, then use the dictionary to print the average rating for each movie, rounded to one decimal.

In [ ]:
# Movie ratings.
movies = ["Monty Python and the Holy Grail", 
          "Monty Python's Life of Brian",
          "Monty Python's Meaning of Life",
          "And Now For Something Completely Different"]

grail_ratings = [ 9, 10, 9.5, 8.5, 3, 7.5,8 ]
brian_ratings = [ 10, 10, 0, 9, 1, 8, 7.5, 8, 6, 9 ]
life_ratings = [ 7, 6, 5 ]
different_ratings = [ 6, 5, 6, 6 ]

list_ratings = [[ 9, 10, 9.5, 8.5, 3, 7.5,8 ], [ 10, 10, 0, 9, 1, 8, 7.5, 8, 6, 9 ], [ 7, 6, 5 ], [ 6, 5, 6, 6 ]]

print(movies.index("Monty Python and the Holy Grail"))
print(list_ratings[0])


dic = {}

for i in movies:
    dic[i] = list_ratings[movies.index(i)]

print (dic)

### Exercise 13.3

A library contains books. Books have a writer, identified by last name and first name. Books also have a title. Books also have a location number that identifies where they can be found in the library. Librarians want to be able to locate a specific book if they know writer and title, and they want to be able to list all the books that they have of a specific writer. What data structure would you use to store the books?

In [ ]:
library = {
    'Libro1': 
    { "name":"Arturo Perez Reverte", "Titulo":"Whatever1", 
      "Location":{'Planta ':1, 'Libreria':2, 'Estante':3} }, 
    'Libro2': 
    { "name":"Frank Kafka", "Titulo":"Understanding Intelligence",
     "Location":{'Planta ':5, 'Libreria':7, 'Estante':9} }, 
    'Libro3': 
    { "name":"Mr. Pumpking ", "Titulo":"Videogames",
     "Location":{'Planta ':5, 'Libreria':9, 'Estante':6, 'Sección':4} } }

for c in library:
    print( "{}: {} ({})".format( c, library[c]["name"], library[c]["Titulo"] ) )
    for s in library[c]["Location"]:
        print( "{}: {}".format( s, library[c]["Location"][s] ) )
    print()

---

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array[[3, 10, 4], [21, 11, 33], [12, 1, 0]]

In [ ]:
pip install pandas

In [43]:
import pandas as pd
df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data", 
    header=None
)

df2 = df[:15000]
df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14970,38,Private,187346,HS-grad,9,Never-married,Sales,Own-child,White,Female,0,0,40,United-States,<=50K
14971,36,Private,108103,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,50,United-States,<=50K
14972,27,Private,255476,5th-6th,3,Never-married,Other-service,Other-relative,White,Male,0,0,40,Mexico,<=50K
14973,24,Private,68577,Assoc-voc,11,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
14974,35,Private,155961,HS-grad,9,Never-married,Other-service,Own-child,Black,Female,0,0,35,Jamaica,<=50K
14975,22,State-gov,264102,Some-college,10,Never-married,Other-service,Other-relative,Black,Male,0,0,39,Haiti,<=50K
14976,37,Private,167777,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,52,United-States,<=50K
14977,36,Private,225399,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,40,United-States,>50K
14978,28,Private,199998,HS-grad,9,Separated,Other-service,Not-in-family,White,Female,0,0,25,United-States,<=50K
14979,55,Private,199856,HS-grad,9,Married-civ-spouse,Sales,Wife,White,Female,0,0,50,United-States,<=50K
14980,29,?,189765,5th-6th,3,Married-civ-spouse,?,Wife,White,Female,0,0,40,United-States,<=50K
14981,32,Private,193042,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,44,United-States,<=50K
14982,66,?,222810,Some-college,10,Divorced,?,Other-relative,White,Female,0,0,35,United-States,<=50K
14983,47,Local-gov,162595,Some-college,10,Married-spouse-absent,Craft-repair,Other-relative,White,Male,0,0,45,United-States,<=50K
14984,23,Private,208826,Bachelors,13,Never-married,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
14985,50,Local-gov,120190,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,45,United-States,<=50K
14986,40,Self-emp-not-inc,27242,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,84,United-States,<=50K
14987,51,Private,348099,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,1590,40,United-States,<=50K
14988,34,Private,185041,HS-grad,9,Never-married,Prof-specialty,Not-in-family,White,Female,0,1669,45,United-States,<=50K
14989,28,Private,309196,Bachelors,13,Never-married,Protective-serv,Not-in-family,White,Female,0,0,40,United-States,<=50K
14990,52,State-gov,254285,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1887,70,Germany,>50K
14991,39,Self-emp-inc,336226,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,3103,0,60,United-States,>50K
14992,43,Private,240698,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,>50K
14993,36,Private,411797,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Female,0,0,35,United-States,>50K
14994,25,Private,178843,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Female,0,0,15,United-States,<=50K
14995,42,Private,136177,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,38,United-States,<=50K
14996,35,Private,243409,Some-college,10,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,Germany,<=50K
14997,43,Private,258049,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,53,United-States,>50K
14998,34,Private,164748,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
14999,50,State-gov,24185,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,38,United-States,>50K

In [42]:
df2.describe()

,0,2,4,10,11,12
count,15000.000000,1.500000e+04,15000.000000,15000.000000,15000.00000,15000.000000
mean,38.521800,1.899806e+05,10.085200,1054.922467,87.31440,40.459867
std,13.645725,1.052111e+05,2.554573,7277.100799,401.36982,12.296506
min,17.000000,1.921400e+04,1.000000,0.000000,0.00000,1.000000
25%,28.000000,1.183700e+05,9.000000,0.000000,0.00000,40.000000
50%,37.000000,1.787050e+05,10.000000,0.000000,0.00000,40.000000
75%,47.000000,2.378850e+05,12.000000,0.000000,0.00000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.00000,99.000000

## Python 2

In [44]:
pd.isnull(df)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32532,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32533,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32534,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32535,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32536,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32537,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32538,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32539,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32540,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32541,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32542,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32543,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32544,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32545,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32546,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32547,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32548,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32549,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32550,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32551,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32552,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32553,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32554,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32555,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32556,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32557,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32558,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32559,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32560,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In Python 2, the methods `keys()`, `values()`, and `items()` return lists instead of iterators.

Python 2 also supports a method `has_key()` that you can use to check if a certain key is in a dictionary, but this method has been removed from Python 3.

---

End of Chapter 14. Version 1.0.